services:
  assetserver:
    environment:
      - ASSETSERVER_DOCKER_ENABLED=true
      - ASSETSERVER_DOCKER_IMAGE=${ASSETSERVER_DOCKER_IMAGE:-assetserver:latest}
      - ASSETSERVER_HOST_ROOT=${PWD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
