name: objaverse
type: objaverse_retrieval
role: retrieve
enabled: false

server:
  host: 127.0.0.1
  port: 7007

params:
  preload_retriever: true
  objaverse_data_path: data/objathor-assets
  objaverse_preprocessed_path: data/objathor-assets/preprocessed
  objaverse_top_k: 5
  clip_device: null
